[project]
name = "week-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.12.5",
    "jina>=3.34.0",
    "requests>=2.32.5",
]
